export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "skyblue",
            padding: "2rem",
          }}
        >
          This is header
        </header>
        {children}
        <footer
          style={{
            padding: "2rem",
            backgroundColor: "yellow",
          }}
        >
          This is footer
        </footer>
      </body>
    </html>
  );
}
